#config-version=FGT60F-7.2.10-FW-build0000-000000:opmode=0:vdom=1:user=admin
config global
 config system global
  set hostname FW-VDOM-DEMO
 end
 config system vdom-link
  edit transit
   set type ethernet
  next
 end
 config system interface
  edit lan
   set vdom branch
   set ip 192.0.2.1 255.255.255.0
  next
  edit transit0
   set vdom branch
   set type vdom-link
   set ip 10.255.0.1 255.255.255.252
  next
  edit transit1
   set vdom root
   set type vdom-link
   set ip 10.255.0.2 255.255.255.252
  next
  edit wan
   set vdom root
   set ip 198.51.100.1 255.255.255.0
  next
 end
end
config vdom
 edit branch
  config router static
   edit 1
    set dst 0.0.0.0 0.0.0.0
    set gateway 10.255.0.2
    set device transit0
   next
  end
  config firewall policy
   edit 1
    set name branch-to-root
    set srcintf lan
    set dstintf transit0
    set srcaddr all
    set dstaddr all
    set service ALL
    set action accept
    set status enable
    set schedule always
    set nat disable
    set logtraffic all
   next
  end
 next
 edit root
  config router static
   edit 1
    set dst 0.0.0.0 0.0.0.0
    set gateway 198.51.100.254
    set device wan
   next
  end
  config firewall policy
   edit 2
    set name root-to-wan
    set srcintf transit1
    set dstintf wan
    set srcaddr all
    set dstaddr all
    set service ALL
    set action accept
    set status enable
    set schedule always
    set nat enable
    set logtraffic all
   next
  end
 next
end
